FROM node:16.10-alpine

# # Install python3.8
# RUN apk update
# RUN apk add --no-cache python3 python3-dev py3-pip gcc libc-dev

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY search-service/package*.json ./

RUN npm install

# # Install pip-dependencies.
# COPY auth/libraries/pip-auth/requirements*.txt ./libraries/pip-auth/
# RUN pip install --no-cache-dir -r ./libraries/pip-auth/requirements.txt -r ./libraries/pip-auth/requirements_development.txt

# Application lays in /app/src
COPY ./search-service ./
COPY search-service/entrypoint.sh ./
COPY search-service/wait-for.sh ./

EXPOSE 9022

ENV OPENSLIDES_DEVELOPMENT 1

ENTRYPOINT [ "./entrypoint.sh" ]
CMD ["npm", "run", "dev"]
